import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "./client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD APPLICATION",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ClientProvider>
  );
}
